site_name: Griptape Trade School
copyright: "&copy; Griptape, Inc."
extra_css:
  - stylesheets/extra.css
theme: 
  name: material
  logo: assets/img/griptape-logo-light.png
  navigation_depth: 2
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    # - navigation.sections
    - navigation.path
    # - navigation.indexes
    - navigation.footer
    # - navigation.expand
    - navigation.prune
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.annotate
    - content.code.copy
    # - navigation.awesome-pages
    - content.code.annotate
  language: en
  palette:
    scheme: slate
    primary: black
    accent: deep orange
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://www.griptape.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/griptape-ai/griptape/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@griptape-ai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/griptape/
markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      title: On this page
      # permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.blocks.details
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

#Navigation       
nav:
  - Home: 
    - Griptape Trade School: 'index.md'
  - Setup: 
    - Setting up for Griptape: setup/index.md
    - Software: setup/01_setting_up_environment.md
    - OpenAI: setup/02_openai.md
    - Griptape: setup/03_griptape.md
    - Resources: setup/04_helpful_resources.md
  - Courses: 
    - All Courses: courses.md
    - Chat bot:
      - Introduction: 200/chatbot-rulesets/index.md
      - Setup: 200/chatbot-rulesets/01_setting_up_environment.md
      - The Chat utility: 200/chatbot-rulesets/03_the_chat_utility.md
      - Hiding the logs: 200/chatbot-rulesets/04_hide_the_logs.md
      - Personality: 200/chatbot-rulesets/05_personality_with_rulesets.md
      - Custom chat: 200/chatbot-rulesets/06_adding_manual_chat.md
      - Manners maketh the bot: 200/chatbot-rulesets/07_manners_maketh_the_bot.md
      - Rulesets for output: 200/chatbot-rulesets/08_adding_another_ruleset_for_output.md
      - Formatting Output: 200/chatbot-rulesets/09_formatting_chat_output.md
      - Markdown Madness: 200/chatbot-rulesets/10_markdown_madness.md
      - Improving the Prompt: 200/chatbot-rulesets/11_gleaming_the_chat.md
      - Multiple Personas: 200/chatbot-rulesets/12_multiple_personas.md
      - Colorful Personality: 200/chatbot-rulesets/13_adding_personality_colors.md
      - Quick Feedback: 200/chatbot-rulesets/14_making_it_quick.md
  - Help: 
    - FAQ: faq.md
    - Contributing: contributing.md
